FROM gradle:jdk21-alpine
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME
ARG GAME
ARG CART
ARG FILTER
ARG ULASAN

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME}
ENV GAME ${GAME}
ENV CART  ${CART}
ENV FILTER  ${FILTER}
ENV ULASAN   ${ULASAN}


WORKDIR /app
RUN ls -al
COPY ./Autentikasi-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java","-jar","Autentikasi-0.0.1-SNAPSHOT.jar"]
